name: AmongHat
author: Get
description: Hallo
version: 1.19

main: com.minecraft.game.amonghat.th.A

commands:
  hbanana:
    description: blahblahblah
    usage: /hbanana
  hblack:
    description: blahblahblah
    usage: /hblack
  hblue:
    description: blahblahblah
    usage: /hblue
  hbrown:
    description: blahblahblah
    usage: /hbrown
  hcoral:
    description: blahblahblah
    usage: /hcoral
  hcyan:
    description: blahblahblah
    usage: /hcyan
  hfortegreen:
    description: blahblahblah
    usage: /hfortegreen
  hgray:
    description: blahblahblah
    usage: /hgray
  hgreen:
    description: blahblahblah
    usage: /hgreen
  hlime:
    description: blahblahblah
    usage: /hlime
  hmaloon:
    description: blahblahblah
    usage: /hmaloon
  holive:
    description: blahblahblah
    usage: /holive
  horange:
    description: blahblahblah
    usage: /horange
  hpink:
    description: blahblahblah
    usage: /hpink
  hpurple:
    description: blahblahblah
    usage: /hpurple
  hred:
    description: blahblahblah
    usage: /hred
  hrose:
    description: blahblahblah
    usage: /hrose
  htan:
    description: blahblahblah
    usage: /htan
  hwhite:
    description: blahblahblah
    usage: /hwhite
  hyellow:
    description: blahblahblah
    usage: /hyellow
  hatall:
    description: blahblahblah
    usage: /hatall
    
  hbigglasses:
    description: blahblahblah
    usage: /hbigglasses
  hcatears:
    description: blahblahblah
    usage: /hcatears
  hglasses:
    description: blahblahblah
    usage: /hglasses
  hthuglifeglasses:
    description: blahblahblah
    usage: /hthuglifeglasses
  accessoryall:
    description: blahblahblah
    usage: /accessoryall                    
    
    